#if !canImport(ObjectiveC)
import XCTest

extension UtilitiesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilitiesTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UtilitiesTests.__allTests__UtilitiesTests),
    ]
}
#endif
